tunnel: df68d104-5c20-44a1-be7c-9b80ff57626a
credentials-file: C:\Users\10847\.cloudflared\df68d104-5c20-44a1-be7c-9b80ff57626a.json

ingress:
  - hostname: hegelsalon.com
    service: http://127.0.0.1:3098
  - hostname: www.hegelsalon.com
    service: http://127.0.0.1:3098
  - hostname: admin.hegelsalon.com
    service: http://127.0.0.1:3098
  - service: http_status:404
